# admin_ui.py - Giao diện cửa sổ Admin (quản lý cửa hàng)
# thêm nút xuất PDF & Excel
# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
logo_path = os.path.join(BASE_DIR, "images", "LOGO2.png").replace("\\", "/")
bg_path = os.path.join(BASE_DIR, "images", "background1.jpg").replace("\\", "/")


class Ui_AdminWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("AdminWindow")
        MainWindow.resize(2196, 1684)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("""
QMainWindow {
    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
        stop:0 #ffecd2, stop:0.5 #fcb69f, stop:1 #ff9a9e);
}
QPushButton {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 #ee609c, stop:1 #b565a7);
    color: white; border: none;
    padding: 12px 24px; border-radius: 12px; font-weight: bold;
}
QPushButton:hover {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 #ff6fab, stop:1 #c471b7);
}
QTableWidget {
    background-color: rgba(255,255,255,0.95);
    border: none; border-radius: 15px;
}
QHeaderView::section {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 #ee609c, stop:1 #b565a7);
    color: white; padding: 12px; border: none;
}
QLineEdit, QComboBox {
    padding: 12px; border: 2px solid #f0e6ef;
    border-radius: 10px; background: rgba(255,255,255,0.9);
}
QLineEdit:focus { border: 2px solid #ee609c; }
QTabWidget::pane {
    border: none; border-radius: 15px;
    background: rgba(255,255,255,0.85);
}
QTabBar::tab {
    background: rgba(255,255,255,0.7);
    padding: 14px 28px; margin-right: 5px;
    border-radius: 12px 12px 0 0;
}
QTabBar::tab:selected {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 #ee609c, stop:1 #b565a7);
    color: white;
}
QGroupBox {
    border: 2px solid rgba(238,96,156,0.3);
    border-radius: 15px; margin-top: 15px;
    background: rgba(255,255,255,0.8);
}
QGroupBox::title { color: #b565a7; font-weight: bold; }
QStatusBar {
    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
        stop:0 #ee609c, stop:1 #b565a7);
    color: white;
}
* { font-family: "Bahnschrift"; }
""")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet(f'''
    QWidget#centralwidget {{
        border-image: url("{bg_path}") 0 0 0 0 stretch stretch;
    }}
''')
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)

        # Title
        self.lblTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitle.setStyleSheet("font-size: 26px; font-weight: bold; color: #e91e63; padding: 20px;")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.verticalLayout.addWidget(self.lblTitle)

        # Tab widget
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("* { font-family: 'Bahnschrift'; font-size: 16px; }")

        # ══ Tab 1: Kho hàng ════════════════════════════════════════════════════
        self.tabInventory = QtWidgets.QWidget()
        vl2 = QtWidgets.QVBoxLayout(self.tabInventory)
        hl = QtWidgets.QHBoxLayout()
        self.txtSearchProduct = QtWidgets.QLineEdit()
        self.txtSearchProduct.setPlaceholderText("🔍 Tìm kiếm sản phẩm...")
        hl.addWidget(self.txtSearchProduct)
        self.cboCategory = QtWidgets.QComboBox()
        for item in ["Tất cả danh mục", "Skincare", "Haircare", "Bodycare",
                     "Sữa rửa mặt", "Toner", "Serum", "Kem dưỡng", "Kem chống nắng"]:
            self.cboCategory.addItem(item)
        hl.addWidget(self.cboCategory)
        self.btnSearchProduct = QtWidgets.QPushButton("Tìm kiếm")
        hl.addWidget(self.btnSearchProduct)
        self.btnRefreshProduct = QtWidgets.QPushButton("🔄 Làm mới")
        self.btnRefreshProduct.setStyleSheet("background-color: #2196F3;")
        hl.addWidget(self.btnRefreshProduct)
        vl2.addLayout(hl)

        self.tblProducts = QtWidgets.QTableWidget()
        self.tblProducts.setAlternatingRowColors(True)
        self.tblProducts.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblProducts.setColumnCount(7)
        self.tblProducts.setHorizontalHeaderLabels(
            ["ID", "Tên sản phẩm", "Danh mục", "Thương hiệu", "Giá", "Số lượng", "Trạng thái"])
        vl2.addWidget(self.tblProducts)

        hl2 = QtWidgets.QHBoxLayout()
        self.btnAddProduct = QtWidgets.QPushButton("➕ Thêm sản phẩm")
        self.btnAddProduct.setStyleSheet("background-color: #4CAF50;")
        hl2.addWidget(self.btnAddProduct)
        self.btnEditProduct = QtWidgets.QPushButton("✏️ Sửa sản phẩm")
        self.btnEditProduct.setStyleSheet("background-color: #FF9800;")
        hl2.addWidget(self.btnEditProduct)
        self.btnDeleteProduct = QtWidgets.QPushButton("🗑️ Xóa sản phẩm")
        self.btnDeleteProduct.setStyleSheet("background-color: #f44336;")
        hl2.addWidget(self.btnDeleteProduct)
        hl2.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum))
        self.btnLowStock = QtWidgets.QPushButton("⚠️ Sắp hết hàng")
        self.btnLowStock.setStyleSheet("background-color: #FF5722;")
        hl2.addWidget(self.btnLowStock)
        self.btnExpired = QtWidgets.QPushButton("⏰ Hết hạn")
        self.btnExpired.setStyleSheet("background-color: #9C27B0;")
        hl2.addWidget(self.btnExpired)
        vl2.addLayout(hl2)
        self.tabWidget.addTab(self.tabInventory, "📦 Kho hàng")

        # ══ Tab 2: Khách hàng ══════════════════════════════════════════════════
        self.tabCustomers = QtWidgets.QWidget()
        vl3 = QtWidgets.QVBoxLayout(self.tabCustomers)
        hl3 = QtWidgets.QHBoxLayout()
        self.txtSearchCustomer = QtWidgets.QLineEdit()
        self.txtSearchCustomer.setPlaceholderText("🔍 Tìm theo tên hoặc SĐT...")
        hl3.addWidget(self.txtSearchCustomer)
        self.btnSearchCustomer = QtWidgets.QPushButton("Tìm kiếm")
        hl3.addWidget(self.btnSearchCustomer)
        self.btnRefreshCustomer = QtWidgets.QPushButton("🔄 Làm mới")
        self.btnRefreshCustomer.setStyleSheet("background-color: #2196F3;")
        hl3.addWidget(self.btnRefreshCustomer)
        vl3.addLayout(hl3)

        self.tblCustomers = QtWidgets.QTableWidget()
        self.tblCustomers.setAlternatingRowColors(True)
        self.tblCustomers.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblCustomers.setColumnCount(7)
        self.tblCustomers.setHorizontalHeaderLabels(
            ["ID", "Họ tên", "SĐT", "Email", "Loại da", "Điểm tích lũy", "Hạng"])
        vl3.addWidget(self.tblCustomers)

        hl4 = QtWidgets.QHBoxLayout()
        self.btnAddCustomer = QtWidgets.QPushButton("➕ Thêm khách hàng")
        self.btnAddCustomer.setStyleSheet("background-color: #4CAF50;")
        hl4.addWidget(self.btnAddCustomer)
        self.btnEditCustomer = QtWidgets.QPushButton("✏️ Sửa thông tin")
        self.btnEditCustomer.setStyleSheet("background-color: #FF9800;")
        hl4.addWidget(self.btnEditCustomer)
        self.btnViewCustomer = QtWidgets.QPushButton("👁️ Xem chi tiết")
        self.btnViewCustomer.setStyleSheet("background-color: #9C27B0;")
        hl4.addWidget(self.btnViewCustomer)
        hl4.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum))
        vl3.addLayout(hl4)
        self.tabWidget.addTab(self.tabCustomers, "👥 Khách hàng")

        # ══ Tab 3: Đơn hàng ════════════════════════════════════════════════════
        self.tabOrders = QtWidgets.QWidget()
        hl7 = QtWidgets.QHBoxLayout(self.tabOrders)

        grp_orders = QtWidgets.QGroupBox("DANH SÁCH ĐƠN HÀNG")
        vl4 = QtWidgets.QVBoxLayout(grp_orders)
        self.tblOrders = QtWidgets.QTableWidget()
        self.tblOrders.setAlternatingRowColors(True)
        self.tblOrders.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblOrders.setColumnCount(5)
        self.tblOrders.setHorizontalHeaderLabels(
            ["Mã ĐH", "Khách hàng", "Ngày", "Tổng tiền", "Trạng thái"])
        vl4.addWidget(self.tblOrders)

        hl5 = QtWidgets.QHBoxLayout()
        self.btnNewOrder = QtWidgets.QPushButton("🛒 Tạo đơn mới")
        self.btnNewOrder.setStyleSheet("background-color: #4CAF50;")
        hl5.addWidget(self.btnNewOrder)
        self.btnViewOrder = QtWidgets.QPushButton("👁️ Xem chi tiết")
        self.btnViewOrder.setStyleSheet("background-color: #9C27B0;")
        hl5.addWidget(self.btnViewOrder)
        self.btnPrintInvoice = QtWidgets.QPushButton("🖨️ In hóa đơn")
        self.btnPrintInvoice.setStyleSheet("background-color: #607D8B;")
        hl5.addWidget(self.btnPrintInvoice)
        # ★ NÚT MỚI: Xuất Excel
        self.btnExportPDF = QtWidgets.QPushButton("📊 Xuất Excel")
        self.btnExportPDF.setStyleSheet("background-color: #217346;")
        hl5.addWidget(self.btnExportPDF)
        vl4.addLayout(hl5)
        hl7.addWidget(grp_orders)

        # Form tạo đơn mới
        grp_new = QtWidgets.QGroupBox("TẠO ĐƠN MỚI:")
        grp_new.setMinimumWidth(400)
        vl5 = QtWidgets.QVBoxLayout(grp_new)
        form = QtWidgets.QFormLayout()
        form.setVerticalSpacing(14)
        self.label = QtWidgets.QLabel("SĐT Khách hàng:")
        self.txtOrderPhone = QtWidgets.QLineEdit()
        self.txtOrderPhone.setPlaceholderText("Nhập SĐT...")
        self.txtOrderPhone.setMinimumHeight(50)
        form.addRow(self.label, self.txtOrderPhone)
        self.label_2 = QtWidgets.QLabel("Tên khách:")
        self.txtOrderCustomerName = QtWidgets.QLineEdit()
        self.txtOrderCustomerName.setReadOnly(True)
        self.txtOrderCustomerName.setPlaceholderText("Tự động điền...")
        self.txtOrderCustomerName.setMinimumHeight(50)
        form.addRow(self.label_2, self.txtOrderCustomerName)
        vl5.addLayout(form)

        self.lineEdit = QtWidgets.QLineEdit("Giỏ hàng:")
        self.lineEdit.setReadOnly(True)
        vl5.addWidget(self.lineEdit)

        self.btnFindCustomer = QtWidgets.QPushButton("🔍 Tìm khách hàng")
        self.btnFindCustomer.setStyleSheet("background-color: #2196F3;")
        vl5.addWidget(self.btnFindCustomer)

        self.tblCart = QtWidgets.QTableWidget()
        self.tblCart.setMaximumHeight(200)
        self.tblCart.setColumnCount(3)
        self.tblCart.setHorizontalHeaderLabels(["Sản phẩm", "SL", "Giá"])
        vl5.addWidget(self.tblCart)

        hl6 = QtWidgets.QHBoxLayout()
        self.btnAddToCart = QtWidgets.QPushButton("➕ Thêm SP")
        self.btnAddToCart.setStyleSheet("background-color: #4CAF50; padding: 8px;")
        hl6.addWidget(self.btnAddToCart)
        self.btnRemoveFromCart = QtWidgets.QPushButton("➖ Xóa SP")
        self.btnRemoveFromCart.setStyleSheet("background-color: #f44336; padding: 8px;")
        hl6.addWidget(self.btnRemoveFromCart)
        vl5.addLayout(hl6)

        self.lblTotal = QtWidgets.QLabel("💰 Tổng: 0đ")
        self.lblTotal.setStyleSheet("font-size: 18px; font-weight: bold; color: #e91e63; padding: 10px;")
        vl5.addWidget(self.lblTotal)

        self.btnCheckout = QtWidgets.QPushButton("✅ THANH TOÁN")
        self.btnCheckout.setStyleSheet("background-color: #4CAF50; font-size: 16px; padding: 15px;")
        vl5.addWidget(self.btnCheckout)
        hl7.addWidget(grp_new)
        self.tabWidget.addTab(self.tabOrders, "🛒 Đơn hàng")

        # ══ Tab 4: Gợi ý SP ════════════════════════════════════════════════════
        self.tabRecommend = QtWidgets.QWidget()
        vl6 = QtWidgets.QVBoxLayout(self.tabRecommend)
        grp3 = QtWidgets.QGroupBox("Thông tin da")
        hl8 = QtWidgets.QHBoxLayout(grp3)
        hl8.addWidget(QtWidgets.QLabel("Loại da:"))
        self.cboSkinType = QtWidgets.QComboBox()
        for st in ["Da dầu", "Da khô", "Da hỗn hợp", "Da thường", "Da nhạy cảm",
                   "Da mụn", "Da lão hóa", "Da nám", "Da thâm"]:
            self.cboSkinType.addItem(st)
        hl8.addWidget(self.cboSkinType)
        hl8.addWidget(QtWidgets.QLabel("Vấn đề da:"))
        self.txtSkinConcerns = QtWidgets.QLineEdit()
        self.txtSkinConcerns.setPlaceholderText("VD: mụn, thâm, khô...")
        hl8.addWidget(self.txtSkinConcerns)
        self.btnGetRecommend = QtWidgets.QPushButton("🔮 Gợi ý sản phẩm")
        hl8.addWidget(self.btnGetRecommend)
        self.btnGetRoutine = QtWidgets.QPushButton("📋 Gợi ý Routine")
        self.btnGetRoutine.setStyleSheet("background-color: #9C27B0;")
        hl8.addWidget(self.btnGetRoutine)
        vl6.addWidget(grp3)

        self.tblRecommend = QtWidgets.QTableWidget()
        self.tblRecommend.setAlternatingRowColors(True)
        self.tblRecommend.setColumnCount(5)
        self.tblRecommend.setHorizontalHeaderLabels(
            ["ID", "Tên sản phẩm", "Danh mục", "Giá", "Mô tả / Công dụng"])
        vl6.addWidget(self.tblRecommend)
        self.tabWidget.addTab(self.tabRecommend, "💄 Gợi ý SP")

        # ══ Tab 5: Chatbot ══════════════════════════════════════════════════════
        self.tabChatbot = QtWidgets.QWidget()
        vl7 = QtWidgets.QVBoxLayout(self.tabChatbot)
        self.txtChatHistory = QtWidgets.QTextEdit()
        self.txtChatHistory.setReadOnly(True)
        self.txtChatHistory.setStyleSheet(
            "background-color: white; border-radius: 8px; padding: 10px; font-size: 14px;")
        self.txtChatHistory.setHtml(
            '<p><b style="color:#7b1fa2;">🤖 Bot:</b> Xin chào! Tôi là trợ lý tư vấn mỹ phẩm AI.<br/>'
            'Bạn có thể cho tôi biết loại da và vấn đề da bạn đang gặp không?</p>')
        vl7.addWidget(self.txtChatHistory)
        hl9 = QtWidgets.QHBoxLayout()
        self.txtChatInput = QtWidgets.QLineEdit()
        self.txtChatInput.setPlaceholderText("Nhập tin nhắn... (VD: Tôi có da dầu và hay bị mụn)")
        hl9.addWidget(self.txtChatInput)
        self.btnSendChat = QtWidgets.QPushButton("📤 Gửi")
        hl9.addWidget(self.btnSendChat)
        self.btnClearChat = QtWidgets.QPushButton("🗑️ Xóa")
        self.btnClearChat.setStyleSheet("background-color: #607D8B;")
        hl9.addWidget(self.btnClearChat)
        vl7.addLayout(hl9)
        self.tabWidget.addTab(self.tabChatbot, "🤖 Chatbot AI")

        # ══ Tab 6: Thống kê ════════════════════════════════════════════════════
        self.tabAnalytics = QtWidgets.QWidget()
        vl8 = QtWidgets.QVBoxLayout(self.tabAnalytics)
        hl10 = QtWidgets.QHBoxLayout()

        grp4 = QtWidgets.QGroupBox("📈 Tổng quan")
        grp4.setStyleSheet("QGroupBox { background-color: white; }")
        vl9 = QtWidgets.QVBoxLayout(grp4)
        self.lblTotalProducts = QtWidgets.QLabel("📦 Tổng sản phẩm: 0")
        self.lblTotalProducts.setStyleSheet("font-size: 16px; padding: 10px;")
        vl9.addWidget(self.lblTotalProducts)
        self.lblTotalCustomers = QtWidgets.QLabel("👥 Tổng khách hàng: 0")
        self.lblTotalCustomers.setStyleSheet("font-size: 16px; padding: 10px;")
        vl9.addWidget(self.lblTotalCustomers)
        self.lblTotalOrders = QtWidgets.QLabel("🛒 Tổng đơn hàng: 0")
        self.lblTotalOrders.setStyleSheet("font-size: 16px; padding: 10px;")
        vl9.addWidget(self.lblTotalOrders)
        self.lblTotalRevenue = QtWidgets.QLabel("💰 Tổng doanh thu: 0đ")
        self.lblTotalRevenue.setStyleSheet(
            "font-size: 18px; padding: 10px; color: #4CAF50; font-weight: bold;")
        vl9.addWidget(self.lblTotalRevenue)
        hl10.addWidget(grp4)

        grp5 = QtWidgets.QGroupBox("🏆 Top sản phẩm bán chạy")
        grp5.setStyleSheet("QGroupBox { background-color: white; }")
        vl10 = QtWidgets.QVBoxLayout(grp5)
        self.tblTopProducts = QtWidgets.QTableWidget()
        self.tblTopProducts.setColumnCount(4)
        self.tblTopProducts.setHorizontalHeaderLabels(["Hạng", "Sản phẩm", "Đã bán", "Doanh thu"])
        vl10.addWidget(self.tblTopProducts)
        hl10.addWidget(grp5)
        vl8.addLayout(hl10)

        grp6 = QtWidgets.QGroupBox("⚠️ Sản phẩm cần nhập thêm")
        grp6.setStyleSheet("QGroupBox { background-color: white; }")
        vl11 = QtWidgets.QVBoxLayout(grp6)
        self.tblLowStock = QtWidgets.QTableWidget()
        self.tblLowStock.setMaximumHeight(200)
        self.tblLowStock.setColumnCount(5)
        self.tblLowStock.setHorizontalHeaderLabels(
            ["Trạng thái", "Sản phẩm", "Tồn kho", "Tối thiểu", "Đề xuất nhập"])
        vl11.addWidget(self.tblLowStock)
        vl8.addWidget(grp6)

        btn_row = QtWidgets.QHBoxLayout()
        self.btnRefreshStats = QtWidgets.QPushButton("🔄 Cập nhật thống kê")
        self.btnRefreshStats.setStyleSheet("background-color: #2196F3;")
        btn_row.addWidget(self.btnRefreshStats)
        # ★ NÚT MỚI: Xuất Excel
        self.btnExportExcel = QtWidgets.QPushButton("📊 Xuất Excel báo cáo")
        self.btnExportExcel.setStyleSheet("background-color: #4CAF50;")
        btn_row.addWidget(self.btnExportExcel)
        btn_row.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                               QtWidgets.QSizePolicy.Policy.Minimum))
        vl8.addLayout(btn_row)
        self.tabWidget.addTab(self.tabAnalytics, "📊 Thống kê")

        # ══ Tab 7: Nhân viên ════════════════════════════════════════════════════
        self.tabStaff = QtWidgets.QWidget()
        vl_staff = QtWidgets.QVBoxLayout(self.tabStaff)
        hl_s = QtWidgets.QHBoxLayout()
        self.txtSearchStaff = QtWidgets.QLineEdit()
        self.txtSearchStaff.setPlaceholderText("🔍 Tìm theo tên hoặc SĐT nhân viên...")
        hl_s.addWidget(self.txtSearchStaff)
        self.cboStaffRole = QtWidgets.QComboBox()
        for r in ["Tất cả chức vụ", "Quản lý", "Thu ngân", "Tư vấn", "Sales"]:
            self.cboStaffRole.addItem(r)
        hl_s.addWidget(self.cboStaffRole)
        self.btnSearchStaff = QtWidgets.QPushButton("Tìm kiếm")
        hl_s.addWidget(self.btnSearchStaff)
        self.btnRefreshStaff = QtWidgets.QPushButton("🔄 Làm mới")
        self.btnRefreshStaff.setStyleSheet("background-color: #2196F3;")
        hl_s.addWidget(self.btnRefreshStaff)
        vl_staff.addLayout(hl_s)

        self.tblStaff = QtWidgets.QTableWidget()
        self.tblStaff.setAlternatingRowColors(True)
        self.tblStaff.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblStaff.setColumnCount(7)
        self.tblStaff.setHorizontalHeaderLabels(
            ["ID", "Họ tên", "SĐT", "Chức vụ", "Ca làm", "Lương", "Trạng thái"])
        vl_staff.addWidget(self.tblStaff)

        hl_sb = QtWidgets.QHBoxLayout()
        self.btnAddStaff = QtWidgets.QPushButton("➕ Thêm nhân viên")
        self.btnAddStaff.setStyleSheet("background-color: #4CAF50;")
        hl_sb.addWidget(self.btnAddStaff)
        self.btnEditStaff = QtWidgets.QPushButton("✏️ Sửa")
        self.btnEditStaff.setStyleSheet("background-color: #FF9800;")
        hl_sb.addWidget(self.btnEditStaff)
        self.btnDeleteStaff = QtWidgets.QPushButton("🗑️ Xóa")
        self.btnDeleteStaff.setStyleSheet("background-color: #f44336;")
        hl_sb.addWidget(self.btnDeleteStaff)
        self.btnAssignShift = QtWidgets.QPushButton("🕒 Phân ca")
        self.btnAssignShift.setStyleSheet("background-color: #9C27B0;")
        hl_sb.addWidget(self.btnAssignShift)
        hl_sb.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum))
        vl_staff.addLayout(hl_sb)
        self.tabWidget.addTab(self.tabStaff, "👨‍💼 Nhân viên")

        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("🧴 NHÓM 6 - Beauty Store - Quản lý (Admin)")
        self.lblTitle.setText(f'''
    <div style="text-align: center;">
        <img src="{logo_path}" width="120"/>
        <br/>
        🧴 NHÓM 6 - BEAUTY STORE - QUẢN LÝ CỬA HÀNG MỸ PHẨM 🧴
    </div>
''')
