# customer_ui.py - Giao diện cổng khách hàng
# Tabs: Sản phẩm | Tìm kiếm | Chi tiết SP | Gợi ý theo da | Chatbot | Giỏ hàng | Lịch sử đơn hàng
# Form implementation generated from reading ui file 'customer.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6 import QtCore, QtGui, QtWidgets
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
logo_path = os.path.join(BASE_DIR, "images", "LOGO2.png").replace("\\", "/")
bg_path = os.path.join(BASE_DIR, "images", "background1.jpg").replace("\\", "/")

CUST_STYLE = """
QMainWindow {
    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
        stop:0 #ffecd2, stop:0.5 #fcb69f, stop:1 #ff9a9e);
}
QPushButton {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 #ee609c, stop:1 #b565a7);
    color: white; border: none;
    padding: 10px 20px; border-radius: 12px; font-weight: bold;
}
QPushButton:hover {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 #ff6fab, stop:1 #c471b7);
}
QTableWidget {
    background-color: rgba(255,255,255,0.95);
    border: none; border-radius: 15px;
}
QHeaderView::section {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 #ee609c, stop:1 #b565a7);
    color: white; padding: 10px; border: none;
}
QLineEdit, QComboBox, QTextEdit {
    padding: 10px; border: 2px solid #f0e6ef;
    border-radius: 10px; background: rgba(255,255,255,0.9);
}
QLineEdit:focus, QTextEdit:focus { border: 2px solid #ee609c; }
QTabWidget::pane {
    border: none; border-radius: 15px;
    background: rgba(255,255,255,0.85);
}
QTabBar::tab {
    background: rgba(255,255,255,0.7);
    padding: 12px 22px; margin-right: 5px;
    border-radius: 12px 12px 0 0; font-size: 14px;
}
QTabBar::tab:selected {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 #ee609c, stop:1 #b565a7);
    color: white;
}
QGroupBox {
    border: 2px solid rgba(238,96,156,0.3);
    border-radius: 15px; margin-top: 15px;
    background: rgba(255,255,255,0.8);
}
QGroupBox::title { color: #b565a7; font-weight: bold; }
QStatusBar {
    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
        stop:0 #ee609c, stop:1 #b565a7);
    color: white;
}
QLabel { color: #444; }
* { font-family: "Bahnschrift"; }
"""


class Ui_CustomerWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("CustomerWindow")
        MainWindow.resize(1600, 1100)
        MainWindow.setStyleSheet(CUST_STYLE)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(f'''
            QWidget#centralwidget {{
                border-image: url("{bg_path}") 0 0 0 0 stretch stretch;
            }}
        ''')
        self.centralwidget.setObjectName("centralwidget")
        main_vl = QtWidgets.QVBoxLayout(self.centralwidget)

        # Header
        self.lblTitle = QtWidgets.QLabel()
        self.lblTitle.setStyleSheet("font-size: 22px; font-weight: bold; color: #e91e63; padding: 16px;")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        main_vl.addWidget(self.lblTitle)

        # Tab widget
        self.tabWidget = QtWidgets.QTabWidget()
        self.tabWidget.setStyleSheet("* { font-family: 'Bahnschrift'; font-size: 15px; }")
        main_vl.addWidget(self.tabWidget)

        # ══ Tab 1: Danh sách sản phẩm ══════════════════════════════════════════
        self.tabProducts = QtWidgets.QWidget()
        vl1 = QtWidgets.QVBoxLayout(self.tabProducts)

        lbl_desc = QtWidgets.QLabel("🌸 Khám phá các sản phẩm mỹ phẩm chất lượng của chúng tôi!")
        lbl_desc.setStyleSheet("color: #b565a7; font-size: 15px; padding: 6px;")
        vl1.addWidget(lbl_desc)

        self.tblProductList = QtWidgets.QTableWidget()
        self.tblProductList.setAlternatingRowColors(True)
        self.tblProductList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblProductList.setColumnCount(6)
        self.tblProductList.setHorizontalHeaderLabels(
            ["ID", "Tên sản phẩm", "Thương hiệu", "Danh mục", "Giá", "Tồn kho"])
        self.tblProductList.horizontalHeader().setSectionResizeMode(
            1, QtWidgets.QHeaderView.ResizeMode.Stretch)
        vl1.addWidget(self.tblProductList)

        hl1 = QtWidgets.QHBoxLayout()
        self.btnViewDetail = QtWidgets.QPushButton("🔍 Xem chi tiết")
        self.btnViewDetail.setStyleSheet("background-color: #9C27B0;")
        hl1.addWidget(self.btnViewDetail)
        self.btnAddToCartFromList = QtWidgets.QPushButton("🛒 Thêm vào giỏ")
        self.btnAddToCartFromList.setStyleSheet("background-color: #4CAF50;")
        hl1.addWidget(self.btnAddToCartFromList)
        hl1.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum))
        self.btnRefreshProducts = QtWidgets.QPushButton("🔄 Làm mới")
        self.btnRefreshProducts.setStyleSheet("background-color: #2196F3;")
        hl1.addWidget(self.btnRefreshProducts)
        vl1.addLayout(hl1)
        self.tabWidget.addTab(self.tabProducts, "🛍️ Sản phẩm")

        # ══ Tab 2: Tìm kiếm ════════════════════════════════════════════════════
        self.tabSearch = QtWidgets.QWidget()
        vl2 = QtWidgets.QVBoxLayout(self.tabSearch)

        grp_search = QtWidgets.QGroupBox("🔍 Tìm kiếm sản phẩm")
        hl_s = QtWidgets.QHBoxLayout(grp_search)
        self.txtSearchKeyword = QtWidgets.QLineEdit()
        self.txtSearchKeyword.setPlaceholderText("Nhập tên sản phẩm, thương hiệu...")
        self.txtSearchKeyword.setMinimumHeight(42)
        hl_s.addWidget(self.txtSearchKeyword)
        hl_s.addWidget(QtWidgets.QLabel("Danh mục:"))
        self.cboSearchCategory = QtWidgets.QComboBox()
        for cat in ["Tất cả", "Skincare", "Haircare", "Bodycare"]:
            self.cboSearchCategory.addItem(cat)
        hl_s.addWidget(self.cboSearchCategory)
        hl_s.addWidget(QtWidgets.QLabel("Giá:"))
        self.cboSearchPrice = QtWidgets.QComboBox()
        for pr in ["Tất cả mức giá", "Dưới 200,000đ", "200,000 - 400,000đ", "Trên 400,000đ"]:
            self.cboSearchPrice.addItem(pr)
        hl_s.addWidget(self.cboSearchPrice)
        self.btnSearch = QtWidgets.QPushButton("🔍 Tìm kiếm")
        hl_s.addWidget(self.btnSearch)
        vl2.addWidget(grp_search)

        self.tblSearchResult = QtWidgets.QTableWidget()
        self.tblSearchResult.setAlternatingRowColors(True)
        self.tblSearchResult.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblSearchResult.setColumnCount(6)
        self.tblSearchResult.setHorizontalHeaderLabels(
            ["ID", "Tên sản phẩm", "Thương hiệu", "Danh mục", "Giá", "Tình trạng"])
        self.tblSearchResult.horizontalHeader().setSectionResizeMode(
            1, QtWidgets.QHeaderView.ResizeMode.Stretch)
        vl2.addWidget(self.tblSearchResult)

        hl_sr = QtWidgets.QHBoxLayout()
        self.btnSearchViewDetail = QtWidgets.QPushButton("🔍 Xem chi tiết")
        self.btnSearchViewDetail.setStyleSheet("background-color: #9C27B0;")
        hl_sr.addWidget(self.btnSearchViewDetail)
        self.btnSearchAddCart = QtWidgets.QPushButton("🛒 Thêm vào giỏ")
        self.btnSearchAddCart.setStyleSheet("background-color: #4CAF50;")
        hl_sr.addWidget(self.btnSearchAddCart)
        hl_sr.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                             QtWidgets.QSizePolicy.Policy.Minimum))
        self.lblSearchCount = QtWidgets.QLabel("Kết quả: 0 sản phẩm")
        self.lblSearchCount.setStyleSheet("color: #888; font-size: 13px;")
        hl_sr.addWidget(self.lblSearchCount)
        vl2.addLayout(hl_sr)
        self.tabWidget.addTab(self.tabSearch, "🔍 Tìm kiếm")

        # ══ Tab 3: Chi tiết sản phẩm ════════════════════════════════════════════
        self.tabProductDetail = QtWidgets.QWidget()
        hl_det = QtWidgets.QHBoxLayout(self.tabProductDetail)

        # Thông tin sản phẩm
        grp_det = QtWidgets.QGroupBox("📦 Thông tin sản phẩm")
        vl_det = QtWidgets.QVBoxLayout(grp_det)
        self.lblProductName = QtWidgets.QLabel("Chọn sản phẩm để xem chi tiết")
        self.lblProductName.setStyleSheet(
            "font-size: 20px; font-weight: bold; color: #e91e63; padding: 8px;")
        self.lblProductName.setWordWrap(True)
        vl_det.addWidget(self.lblProductName)

        form_det = QtWidgets.QFormLayout()
        form_det.setVerticalSpacing(10)
        for lbl_text, attr in [
            ("Thương hiệu:", "lblDetailBrand"),
            ("Danh mục:", "lblDetailCategory"),
            ("Giá:", "lblDetailPrice"),
            ("Tồn kho:", "lblDetailStock"),
            ("Loại da phù hợp:", "lblDetailSkinType"),
            ("Công dụng:", "lblDetailEffects"),
            ("Thành phần:", "lblDetailIngredients"),
        ]:
            lbl = QtWidgets.QLabel("—")
            lbl.setStyleSheet("color: #444; font-size: 14px;")
            lbl.setWordWrap(True)
            setattr(self, attr, lbl)
            form_det.addRow(QtWidgets.QLabel(f"<b>{lbl_text}</b>"), lbl)
        vl_det.addLayout(form_det)
        vl_det.addStretch()

        hl_det_btn = QtWidgets.QHBoxLayout()
        self.spinDetailQty = QtWidgets.QSpinBox()
        self.spinDetailQty.setMinimum(1)
        self.spinDetailQty.setMaximum(99)
        self.spinDetailQty.setValue(1)
        self.spinDetailQty.setPrefix("SL: ")
        self.spinDetailQty.setMinimumHeight(40)
        hl_det_btn.addWidget(self.spinDetailQty)
        self.btnDetailAddCart = QtWidgets.QPushButton("🛒 Thêm vào giỏ hàng")
        self.btnDetailAddCart.setStyleSheet("background-color: #4CAF50; font-size: 15px; padding: 12px;")
        hl_det_btn.addWidget(self.btnDetailAddCart)
        vl_det.addLayout(hl_det_btn)
        hl_det.addWidget(grp_det, 3)

        # Sản phẩm liên quan
        grp_related = QtWidgets.QGroupBox("💡 Sản phẩm tương tự")
        vl_rel = QtWidgets.QVBoxLayout(grp_related)
        self.tblRelated = QtWidgets.QTableWidget()
        self.tblRelated.setColumnCount(4)
        self.tblRelated.setHorizontalHeaderLabels(["Tên", "Thương hiệu", "Giá", "Công dụng"])
        self.tblRelated.horizontalHeader().setSectionResizeMode(
            0, QtWidgets.QHeaderView.ResizeMode.Stretch)
        vl_rel.addWidget(self.tblRelated)
        hl_det.addWidget(grp_related, 2)
        self.tabWidget.addTab(self.tabProductDetail, "📋 Chi tiết SP")

        # ══ Tab 4: Gợi ý theo da ════════════════════════════════════════════════
        self.tabSkinRecommend = QtWidgets.QWidget()
        vl4 = QtWidgets.QVBoxLayout(self.tabSkinRecommend)

        grp_skin = QtWidgets.QGroupBox("🌸 Thông tin da của bạn")
        form_skin = QtWidgets.QFormLayout(grp_skin)
        form_skin.setVerticalSpacing(12)
        form_skin.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight)

        self.cboMySkinType = QtWidgets.QComboBox()
        for st in ["-- Chọn loại da --", "Da dầu", "Da khô", "Da hỗn hợp",
                   "Da nhạy cảm", "Da thường", "Da mụn", "Da lão hóa", "Da nám", "Da thâm"]:
            self.cboMySkinType.addItem(st)
        self.cboMySkinType.setMinimumHeight(40)
        form_skin.addRow("<b>Loại da:</b>", self.cboMySkinType)

        self.txtMySkinConcerns = QtWidgets.QLineEdit()
        self.txtMySkinConcerns.setPlaceholderText("VD: mụn, thâm, khô, dầu... (cách nhau bởi dấu phẩy)")
        self.txtMySkinConcerns.setMinimumHeight(40)
        form_skin.addRow("<b>Vấn đề da:</b>", self.txtMySkinConcerns)
        vl4.addWidget(grp_skin)

        hl_rec = QtWidgets.QHBoxLayout()
        self.btnGetMyRecommend = QtWidgets.QPushButton("🔮 Gợi ý sản phẩm phù hợp")
        self.btnGetMyRecommend.setStyleSheet("font-size: 15px; padding: 12px;")
        hl_rec.addWidget(self.btnGetMyRecommend)
        self.btnGetMyRoutine = QtWidgets.QPushButton("📋 Tạo Routine cho tôi")
        self.btnGetMyRoutine.setStyleSheet("background-color: #9C27B0; font-size: 15px; padding: 12px;")
        hl_rec.addWidget(self.btnGetMyRoutine)
        hl_rec.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                              QtWidgets.QSizePolicy.Policy.Minimum))
        vl4.addLayout(hl_rec)

        self.tblMyRecommend = QtWidgets.QTableWidget()
        self.tblMyRecommend.setAlternatingRowColors(True)
        self.tblMyRecommend.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblMyRecommend.setColumnCount(5)
        self.tblMyRecommend.setHorizontalHeaderLabels(
            ["ID", "Tên sản phẩm", "Thương hiệu", "Giá", "Công dụng"])
        self.tblMyRecommend.horizontalHeader().setSectionResizeMode(
            1, QtWidgets.QHeaderView.ResizeMode.Stretch)
        vl4.addWidget(self.tblMyRecommend)

        hl4_btn = QtWidgets.QHBoxLayout()
        self.btnRecAddCart = QtWidgets.QPushButton("🛒 Thêm SP được chọn vào giỏ")
        self.btnRecAddCart.setStyleSheet("background-color: #4CAF50;")
        hl4_btn.addWidget(self.btnRecAddCart)
        hl4_btn.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                               QtWidgets.QSizePolicy.Policy.Minimum))
        vl4.addLayout(hl4_btn)
        self.tabWidget.addTab(self.tabSkinRecommend, "💆 Gợi ý theo da")

        # ══ Tab 5: Chatbot ══════════════════════════════════════════════════════
        self.tabChatbot = QtWidgets.QWidget()
        vl5 = QtWidgets.QVBoxLayout(self.tabChatbot)

        self.txtChatHistory = QtWidgets.QTextEdit()
        self.txtChatHistory.setReadOnly(True)
        self.txtChatHistory.setStyleSheet(
            "background-color: white; border-radius: 12px; padding: 12px; font-size: 14px;")
        self.txtChatHistory.setHtml(
            '<p><b style="color:#7b1fa2;">🤖 Bot:</b> Xin chào! Tôi là trợ lý tư vấn mỹ phẩm AI.<br/>'
            'Hãy cho tôi biết loại da và vấn đề da bạn đang gặp nhé! 💖</p>')
        vl5.addWidget(self.txtChatHistory)

        hl5 = QtWidgets.QHBoxLayout()
        self.txtChatInput = QtWidgets.QLineEdit()
        self.txtChatInput.setPlaceholderText("Nhập tin nhắn... (VD: Tôi có da dầu và hay bị mụn)")
        self.txtChatInput.setMinimumHeight(44)
        hl5.addWidget(self.txtChatInput)
        self.btnSendChat = QtWidgets.QPushButton("📤 Gửi")
        self.btnSendChat.setMinimumHeight(44)
        hl5.addWidget(self.btnSendChat)
        self.btnClearChat = QtWidgets.QPushButton("🗑️ Xóa")
        self.btnClearChat.setStyleSheet("background-color: #607D8B;")
        self.btnClearChat.setMinimumHeight(44)
        hl5.addWidget(self.btnClearChat)
        vl5.addLayout(hl5)

        # Quick-reply buttons
        quick_lbl = QtWidgets.QLabel("Gợi ý nhanh:")
        quick_lbl.setStyleSheet("color: #888; font-size: 12px;")
        vl5.addWidget(quick_lbl)
        hl_quick = QtWidgets.QHBoxLayout()
        for txt in ["Da dầu", "Da khô", "Da nhạy cảm", "Bị mụn", "Gợi ý serum", "Routine skincare"]:
            btn = QtWidgets.QPushButton(txt)
            btn.setStyleSheet(
                "background: rgba(238,96,156,0.15); color: #e91e63; "
                "border: 1px solid #ee609c; border-radius: 12px; padding: 6px 14px; font-size: 12px;")
            btn.setObjectName(f"quickBtn_{txt.replace(' ', '_')}")
            hl_quick.addWidget(btn)
        hl_quick.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                                QtWidgets.QSizePolicy.Policy.Minimum))
        vl5.addLayout(hl_quick)
        self.tabWidget.addTab(self.tabChatbot, "🤖 Chatbot AI")

        # ══ Tab 6: Giỏ hàng ════════════════════════════════════════════════════
        self.tabCart = QtWidgets.QWidget()
        hl6 = QtWidgets.QHBoxLayout(self.tabCart)

        # Bảng giỏ hàng
        grp_cart = QtWidgets.QGroupBox("🛒 Giỏ hàng của bạn")
        vl_cart = QtWidgets.QVBoxLayout(grp_cart)
        self.tblCart = QtWidgets.QTableWidget()
        self.tblCart.setAlternatingRowColors(True)
        self.tblCart.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblCart.setColumnCount(5)
        self.tblCart.setHorizontalHeaderLabels(
            ["ID", "Tên sản phẩm", "Đơn giá", "SL", "Thành tiền"])
        self.tblCart.horizontalHeader().setSectionResizeMode(
            1, QtWidgets.QHeaderView.ResizeMode.Stretch)
        vl_cart.addWidget(self.tblCart)

        hl_cart_btn = QtWidgets.QHBoxLayout()
        self.btnCartRemove = QtWidgets.QPushButton("➖ Xóa sản phẩm")
        self.btnCartRemove.setStyleSheet("background-color: #f44336;")
        hl_cart_btn.addWidget(self.btnCartRemove)
        self.btnCartClear = QtWidgets.QPushButton("🗑️ Xóa tất cả")
        self.btnCartClear.setStyleSheet("background-color: #9E9E9E;")
        hl_cart_btn.addWidget(self.btnCartClear)
        hl_cart_btn.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                                   QtWidgets.QSizePolicy.Policy.Minimum))
        vl_cart.addLayout(hl_cart_btn)
        hl6.addWidget(grp_cart, 3)

        # Panel thanh toán
        grp_checkout = QtWidgets.QGroupBox("💳 Thanh toán")
        grp_checkout.setMinimumWidth(320)
        vl_co = QtWidgets.QVBoxLayout(grp_checkout)
        vl_co.setSpacing(14)

        self.lblCartSubtotal = QtWidgets.QLabel("Tạm tính: 0đ")
        self.lblCartSubtotal.setStyleSheet("font-size: 15px; padding: 6px;")
        vl_co.addWidget(self.lblCartSubtotal)

        self.lblCartDiscount = QtWidgets.QLabel("Giảm giá (0%): -0đ")
        self.lblCartDiscount.setStyleSheet("font-size: 14px; color: #4CAF50; padding: 6px;")
        vl_co.addWidget(self.lblCartDiscount)

        self.lblCartTotal = QtWidgets.QLabel("💰 TỔNG: 0đ")
        self.lblCartTotal.setStyleSheet(
            "font-size: 20px; font-weight: bold; color: #e91e63; padding: 10px;")
        vl_co.addWidget(self.lblCartTotal)

        sep = QtWidgets.QFrame()
        sep.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        sep.setStyleSheet("border: 1px solid #f0e6ef;")
        vl_co.addWidget(sep)

        vl_co.addWidget(QtWidgets.QLabel("Ghi chú đơn hàng:"))
        self.txtOrderNote = QtWidgets.QLineEdit()
        self.txtOrderNote.setPlaceholderText("Ghi chú cho shop...")
        vl_co.addWidget(self.txtOrderNote)

        vl_co.addStretch()
        self.btnPlaceOrder = QtWidgets.QPushButton("✅ ĐẶT HÀNG NGAY")
        self.btnPlaceOrder.setStyleSheet(
            "background-color: #4CAF50; font-size: 16px; padding: 18px; border-radius: 14px;")
        self.btnPlaceOrder.setMinimumHeight(56)
        vl_co.addWidget(self.btnPlaceOrder)
        hl6.addWidget(grp_checkout, 1)
        self.tabWidget.addTab(self.tabCart, "🛒 Giỏ hàng")

        # ══ Tab 7: Lịch sử đơn hàng ════════════════════════════════════════════
        self.tabOrderHistory = QtWidgets.QWidget()
        vl7 = QtWidgets.QVBoxLayout(self.tabOrderHistory)

        lbl_hist = QtWidgets.QLabel("📋 Lịch sử mua hàng của bạn")
        lbl_hist.setStyleSheet("font-size: 18px; font-weight: bold; color: #e91e63; padding: 8px;")
        vl7.addWidget(lbl_hist)

        self.tblOrderHistory = QtWidgets.QTableWidget()
        self.tblOrderHistory.setAlternatingRowColors(True)
        self.tblOrderHistory.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblOrderHistory.setColumnCount(5)
        self.tblOrderHistory.setHorizontalHeaderLabels(
            ["Mã đơn", "Ngày đặt", "Số sản phẩm", "Tổng tiền", "Trạng thái"])
        self.tblOrderHistory.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.ResizeMode.Stretch)
        vl7.addWidget(self.tblOrderHistory)

        hl7 = QtWidgets.QHBoxLayout()
        self.btnViewHistoryDetail = QtWidgets.QPushButton("👁️ Xem chi tiết đơn hàng")
        self.btnViewHistoryDetail.setStyleSheet("background-color: #9C27B0;")
        hl7.addWidget(self.btnViewHistoryDetail)
        self.btnRefreshHistory = QtWidgets.QPushButton("🔄 Làm mới")
        self.btnRefreshHistory.setStyleSheet("background-color: #2196F3;")
        hl7.addWidget(self.btnRefreshHistory)
        hl7.addItem(QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum))
        self.lblHistoryTotal = QtWidgets.QLabel("Tổng chi tiêu: 0đ | Số đơn: 0")
        self.lblHistoryTotal.setStyleSheet("font-size: 14px; font-weight: bold; color: #e91e63;")
        hl7.addWidget(self.lblHistoryTotal)
        vl7.addLayout(hl7)
        self.tabWidget.addTab(self.tabOrderHistory, "📜 Lịch sử ĐH")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle("🧴 GLOWUP Beauty Store - Cổng Khách hàng")
        self.lblTitle.setText(f'''
    <div style="text-align:center;">
        <img src="{logo_path}" width="90"/>
        &nbsp;&nbsp;
        🧴 NNHÓM 6 - BEAUTY STORE - Chào mừng bạn! 💖
    </div>
''')
