# login_ui.py - Giao diện màn hình đăng nhập / đăng ký

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
logo_path = os.path.join(BASE_DIR, "images", "LOGO2.png").replace("\\", "/")
bg_path = os.path.join(BASE_DIR, "images", "background1.jpg").replace("\\", "/")

GLOBAL_STYLE = """
QWidget {
    font-family: "Bahnschrift";
    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
        stop:0 #ffecd2, stop:0.5 #fcb69f, stop:1 #ff9a9e);
}
QLineEdit {
    padding: 12px 16px;
    border: 2px solid #f0e6ef;
    border-radius: 10px;
    background: rgba(255,255,255,0.9);
    font-size: 14px;
}
QLineEdit:focus {
    border: 2px solid #ee609c;
}
QPushButton {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 #ee609c, stop:1 #b565a7);
    color: white;
    border: none;
    padding: 12px 24px;
    border-radius: 12px;
    font-weight: bold;
    font-size: 14px;
}
QPushButton:hover {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 #ff6fab, stop:1 #c471b7);
}
QPushButton#btnRegisterSwitch {
    background: transparent;
    color: #b565a7;
    border: 2px solid #b565a7;
    font-size: 13px;
    padding: 8px 20px;
}
QPushButton#btnRegisterSwitch:hover {
    background: rgba(181,101,167,0.1);
}
QPushButton#btnBackToLogin {
    background: transparent;
    color: #888;
    border: 1px solid #ccc;
    font-size: 12px;
    padding: 6px 16px;
}
QPushButton#btnBackToLogin:hover {
    background: rgba(0,0,0,0.05);
}
QLabel#lblTitle {
    font-size: 24px;
    font-weight: bold;
    color: #e91e63;
}
QLabel#lblSubtitle {
    font-size: 13px;
    color: #888;
}
QLabel {
    font-size: 13px;
    color: #555;
    background: transparent;
}
QFrame#cardFrame {
    background: rgba(255,255,255,0.92);
    border-radius: 20px;
    border: 1px solid rgba(238,96,156,0.2);
}
QTabWidget::pane { border: none; background: transparent; }
QTabBar::tab {
    background: rgba(255,255,255,0.7);
    padding: 10px 24px;
    border-radius: 10px 10px 0 0;
    margin-right: 4px;
    font-size: 13px;
    color: #888;
}
QTabBar::tab:selected {
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 #ee609c, stop:1 #b565a7);
    color: white;
    font-weight: bold;
}
"""


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(900, 620)
        LoginWindow.setStyleSheet(GLOBAL_STYLE)

        # Central widget
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet(f"""
            QWidget#centralwidget {{
                border-image: url("{bg_path}") 0 0 0 0 stretch stretch;
            }}
        """)
        main_layout = QtWidgets.QHBoxLayout(self.centralwidget)
        main_layout.setContentsMargins(0, 0, 0, 0)

        # ── Left panel: branding ──────────────────────────────────────────────
        left = QtWidgets.QWidget()
        left.setStyleSheet("""
            QWidget {
                background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
                    stop:0 rgba(238,96,156,0.85), stop:1 rgba(181,101,167,0.85));
                border-radius: 0px;
            }
        """)
        left.setMinimumWidth(320)
        left_layout = QtWidgets.QVBoxLayout(left)
        left_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        left_layout.setSpacing(20)

        logo_lbl = QtWidgets.QLabel()
        logo_lbl.setPixmap(QtGui.QPixmap(logo_path).scaled(
            140, 140, QtCore.Qt.AspectRatioMode.KeepAspectRatio,
            QtCore.Qt.TransformationMode.SmoothTransformation))
        logo_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        logo_lbl.setStyleSheet("background: transparent;")
        left_layout.addWidget(logo_lbl)

        brand_lbl = QtWidgets.QLabel("GLOWUP\nBEAUTY STORE")
        brand_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        brand_lbl.setStyleSheet("""
            font-size: 22px; font-weight: bold; color: white;
            letter-spacing: 2px; background: transparent;
        """)
        left_layout.addWidget(brand_lbl)

        tagline = QtWidgets.QLabel("✨ Tư vấn skincare thông minh\n💄 Mua sắm tiện lợi\n🤖 Chatbot AI hỗ trợ 24/7")
        tagline.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        tagline.setStyleSheet("font-size: 13px; color: rgba(255,255,255,0.9); background: transparent;")
        left_layout.addWidget(tagline)

        main_layout.addWidget(left)

        # ── Right panel: login/register form ─────────────────────────────────
        right = QtWidgets.QWidget()
        right.setStyleSheet("QWidget { background: transparent; }")
        right_layout = QtWidgets.QVBoxLayout(right)
        right_layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        right_layout.setContentsMargins(40, 40, 40, 40)

        # Card frame
        self.cardFrame = QtWidgets.QFrame()
        self.cardFrame.setObjectName("cardFrame")
        self.cardFrame.setMinimumWidth(400)
        self.cardFrame.setMaximumWidth(460)
        card_layout = QtWidgets.QVBoxLayout(self.cardFrame)
        card_layout.setContentsMargins(36, 32, 36, 32)
        card_layout.setSpacing(16)

        # Stacked widget: Login page + Register page
        self.stackedWidget = QtWidgets.QStackedWidget()
        self.stackedWidget.setStyleSheet("background: transparent;")

        # ── Page 0: Login ─────────────────────────────────────────────────────
        self.pageLogin = QtWidgets.QWidget()
        self.pageLogin.setStyleSheet("background: transparent;")
        login_layout = QtWidgets.QVBoxLayout(self.pageLogin)
        login_layout.setSpacing(14)

        self.lblTitle = QtWidgets.QLabel("Đăng nhập")
        self.lblTitle.setObjectName("lblTitle")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        login_layout.addWidget(self.lblTitle)

        self.lblSubtitle = QtWidgets.QLabel("Chào mừng trở lại! Vui lòng đăng nhập.")
        self.lblSubtitle.setObjectName("lblSubtitle")
        self.lblSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        login_layout.addWidget(self.lblSubtitle)
        login_layout.addSpacing(8)

        lbl_user = QtWidgets.QLabel("Tên đăng nhập")
        login_layout.addWidget(lbl_user)
        self.txtUsername = QtWidgets.QLineEdit()
        self.txtUsername.setPlaceholderText("Nhập tên đăng nhập...")
        self.txtUsername.setMinimumHeight(44)
        login_layout.addWidget(self.txtUsername)

        lbl_pass = QtWidgets.QLabel("Mật khẩu")
        login_layout.addWidget(lbl_pass)
        self.txtPassword = QtWidgets.QLineEdit()
        self.txtPassword.setPlaceholderText("Nhập mật khẩu...")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setMinimumHeight(44)
        login_layout.addWidget(self.txtPassword)

        self.lblLoginError = QtWidgets.QLabel("")
        self.lblLoginError.setStyleSheet("color: #f44336; font-size: 12px; background: transparent;")
        self.lblLoginError.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        login_layout.addWidget(self.lblLoginError)

        self.btnLogin = QtWidgets.QPushButton("🔐 Đăng nhập")
        self.btnLogin.setMinimumHeight(46)
        self.btnLogin.setObjectName("btnLogin")
        login_layout.addWidget(self.btnLogin)

        login_layout.addSpacing(4)
        sep_lbl = QtWidgets.QLabel("─── hoặc ───")
        sep_lbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        sep_lbl.setStyleSheet("color: #bbb; font-size: 11px; background: transparent;")
        login_layout.addWidget(sep_lbl)

        self.btnRegisterSwitch = QtWidgets.QPushButton("Đăng ký tài khoản khách hàng")
        self.btnRegisterSwitch.setObjectName("btnRegisterSwitch")
        self.btnRegisterSwitch.setMinimumHeight(40)
        login_layout.addWidget(self.btnRegisterSwitch)

        self.stackedWidget.addWidget(self.pageLogin)

        # ── Page 1: Register ──────────────────────────────────────────────────
        self.pageRegister = QtWidgets.QWidget()
        self.pageRegister.setStyleSheet("background: transparent;")
        reg_layout = QtWidgets.QVBoxLayout(self.pageRegister)
        reg_layout.setSpacing(10)

        lbl_reg_title = QtWidgets.QLabel("Đăng ký tài khoản")
        lbl_reg_title.setObjectName("lblTitle")
        lbl_reg_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        reg_layout.addWidget(lbl_reg_title)

        for lbl_text, attr, placeholder, is_pass in [
            ("Họ và tên", "txtRegName", "Nguyễn Thị A...", False),
            ("Số điện thoại", "txtRegPhone", "09xxxxxxxx", False),
            ("Tên đăng nhập", "txtRegUsername", "username...", False),
            ("Mật khẩu", "txtRegPassword", "ít nhất 4 ký tự", True),
        ]:
            lbl = QtWidgets.QLabel(lbl_text)
            reg_layout.addWidget(lbl)
            field = QtWidgets.QLineEdit()
            field.setPlaceholderText(placeholder)
            field.setMinimumHeight(40)
            if is_pass:
                field.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
            setattr(self, attr, field)
            reg_layout.addWidget(field)

        self.lblRegError = QtWidgets.QLabel("")
        self.lblRegError.setStyleSheet("color: #f44336; font-size: 12px; background: transparent;")
        self.lblRegError.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        reg_layout.addWidget(self.lblRegError)

        self.btnRegister = QtWidgets.QPushButton("✅ Tạo tài khoản")
        self.btnRegister.setMinimumHeight(44)
        reg_layout.addWidget(self.btnRegister)

        self.btnBackToLogin = QtWidgets.QPushButton("← Quay lại đăng nhập")
        self.btnBackToLogin.setObjectName("btnBackToLogin")
        self.btnBackToLogin.setMinimumHeight(36)
        reg_layout.addWidget(self.btnBackToLogin)

        self.stackedWidget.addWidget(self.pageRegister)

        card_layout.addWidget(self.stackedWidget)
        right_layout.addWidget(self.cardFrame)
        main_layout.addWidget(right)

        LoginWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(LoginWindow)

    def retranslateUi(self, LoginWindow):
        LoginWindow.setWindowTitle("NHÓM 6- Beauty Store - Đăng nhập")
